apiVersion: apps/v1
kind: Deployment
metadata:
  name: hserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hserver
  template:
    metadata:
      labels:
        app: hserver
    spec:
      containers:
        - name: hserver
          image: himanshurajora/hserver
          ports:
            - containerPort: 3000
          imagePullPolicy: Never
